Add strict mode to DefinitionStorage
yiisoft/definitions pull request #25
Opened 2021-11-26 21:51 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2021-11-27 15:08 UTC, rustamwin approved these changes

2021-11-28 05:52 UTC, vjik requested changes
If use `DefinitionStorage::get()` wthout run before `DefinitionStorage::has()`, then storage always work as strict. Should it be like this?

2021-11-28 05:52 UTC, vjik commented on tests/Unit/DefinitionStorageTest.php
> +use NonExisting;
```suggestion
```

2021-11-28 05:52 UTC, vjik commented on tests/Unit/DefinitionStorageTest.php
> +        $this->expectException(RuntimeException::class);
```suggestion
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Service ' . EngineMarkOne::class . ' doesn\'t exist in DefinitionStorage.');
```

2021-11-28 05:52 UTC, vjik commented on src/DefinitionStorage.php
> +            return false;
Should we add ID into build stack here?

2021-11-29 10:05 UTC, merged