In methods of array definitions add autowiring and improve variadic arguments support
yiisoft/definitions pull request #44
Opened 2022-10-29 08:11 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | -

2022-10-29 20:11 UTC, rustamwin approved these changes

2022-10-31 08:19 UTC, rustamwin requested changes

2022-10-31 08:19 UTC, rustamwin commented on tests/Unit/ArrayDefinitionTest.php
> +                ['name' => 'kitty', 'colors' => [1, 2, 3]],
Need a test with `Reference` and tags

2022-10-31 08:44 UTC, vjik commented on tests/Unit/ArrayDefinitionTest.php
> +                ['name' => 'kitty', 'colors' => [1, 2, 3]],
fixed and add tests

2022-10-31 09:23 UTC, rustamwin approved these changes
👍

2022-10-31 10:12 UTC, merged